.TH {{ cookiecutter.project_name }} 1 "{% now 'local', '%d %b %Y' %}" {{ cookiecutter.project_name }} "{{ cookiecutter.project_name }} manual"
.SH NAME
{{ cookiecutter.project_name }} \- {{ cookiecutter.project_short_description }}
.SH SYNOPSIS
{{ cookiecutter.project_name }}
.SH DESCRIPTION
{{ cookiecutter.project_short_description }}
.SH OPTIONS

.SH SEE ALSO

.SH BUGS
No known bugs.
.SH AUTHOR
{{ cookiecutter.author_name }} ({{ cookiecutter.author_email }})
